name: Email Action Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 23f3004267@ds.study.iitm.ac.in
        run: echo "Hello, world!"
